[package]
name = "anif"
version = "0.1.0"
authors = ["Lane Arnold <48893038+Lane-A@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

hex = "0.4.2"
hex_d_hex = "1.0.1"
